### ISSUE TITLE
Problem installing flashgamma

### ISSUE THREAD

**Issue by kaphleamrit2** [samuelpeet/flashgamma#11]
Hi,

I tried to pip install flashgamma (anaconda prompt) but it shows an error. Any solution to solve this issue?

`(MyEnvironmentName1) C:\WINDOWS\system32>pip3 install flashgamma
Collecting flashgamma
  Using cached flashgamma-0.0.1.tar.gz (125 kB)
Requirement already satisfied: numpy in c:\users\kaphl\.conda\envs\myenvironmentname1\lib\site-packages (from flashgamma) (1.20.3)
Requirement already satisfied: scipy in c:\users\kaphl\.conda\envs\myenvironmentname1\lib\site-packages (from flashgamma) (1.6.3)
Building wheels for collected packages: flashgamma
  Building wheel for flashgamma (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\kaphl\.conda\envs\myenvironmentname1\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kaphl\\AppData\\Local\\Temp\\pip-install-hr3tzs6r\\flashgamma_663340304374467a8931fe3ce96d00c3\\setup.py'"'"'; __file__='"'"'C:\\Users\\kaphl\\AppData\\Local\\Temp\\pip-install-hr3tzs6r\\flashgamma_663340304374467a8931fe3ce96d00c3\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\kaphl\AppData\Local\Temp\pip-wheel-kyvh2p_p'
       cwd: C:\Users\kaphl\AppData\Local\Temp\pip-install-hr3tzs6r\flashgamma_663340304374467a8931fe3ce96d00c3\
  Complete output (35 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.9
  creating build\lib.win-amd64-3.9\flashgamma
  copying flashgamma\algorithms.py -> build\lib.win-amd64-3.9\flashgamma
  copying flashgamma\distribution.py -> build\lib.win-amd64-3.9\flashgamma
  copying flashgamma\helpers.py -> build\lib.win-amd64-3.9\flashgamma
  copying flashgamma\__init__.py -> build\lib.win-amd64-3.9\flashgamma
  running build_ext
  building 'flashgamma.gamma_evaluation_c' extension
  creating build\temp.win-amd64-3.9
  creating build\temp.win-amd64-3.9\Release
  creating build\temp.win-amd64-3.9\Release\flashgamma
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\kaphl\.conda\envs\myenvironmentname1\lib\site-packages\numpy\core\include -Ic:\users\kaphl\.conda\envs\myenvironmentname1\include -Ic:\users\kaphl\.conda\envs\myenvironmentname1\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcflashgamma/gamma_evaluation_c.c /Fobuild\temp.win-amd64-3.9\Release\flashgamma/gamma_evaluation_c.obj
  gamma_evaluation_c.c
  c:\users\kaphl\.conda\envs\myenvironmentname1\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
  flashgamma/gamma_evaluation_c.c(2923): warning C4018: '<': signed/unsigned mismatch
  flashgamma/gamma_evaluation_c.c(2935): warning C4018: '<': signed/unsigned mismatch
  flashgamma/gamma_evaluation_c.c(3194): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
  flashgamma/gamma_evaluation_c.c(3205): warning C4018: '<': signed/unsigned mismatch
  flashgamma/gamma_evaluation_c.c(3217): warning C4018: '<': signed/unsigned mismatch
  flashgamma/gamma_evaluation_c.c(19801): error C2039: 'tp_print': is not a member of '_typeobject'
  c:\users\kaphl\.conda\envs\myenvironmentname1\include\cpython/object.h(193): note: see declaration of '_typeobject'
  flashgamma/gamma_evaluation_c.c(19806): error C2039: 'tp_print': is not a member of '_typeobject'
  c:\users\kaphl\.conda\envs\myenvironmentname1\include\cpython/object.h(193): note: see declaration of '_typeobject'
  flashgamma/gamma_evaluation_c.c(19821): error C2039: 'tp_print': is not a member of '_typeobject'
  c:\users\kaphl\.conda\envs\myenvironmentname1\include\cpython/object.h(193): note: see declaration of '_typeobject'
  flashgamma/gamma_evaluation_c.c(19834): error C2039: 'tp_print': is not a member of '_typeobject'
  c:\users\kaphl\.conda\envs\myenvironmentname1\include\cpython/object.h(193): note: see declaration of '_typeobject'
  flashgamma/gamma_evaluation_c.c(20434): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
  flashgamma/gamma_evaluation_c.c(20450): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
  flashgamma/gamma_evaluation_c.c(22022): warning C4996: 'PyUnicode_FromUnicode': deprecated in 3.3
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for flashgamma
  Running setup.py clean for flashgamma
Failed to build flashgamma
Installing collected packages: flashgamma
    Running setup.py install for flashgamma ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\kaphl\.conda\envs\myenvironmentname1\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kaphl\\AppData\\Local\\Temp\\pip-install-hr3tzs6r\\flashgamma_663340304374467a8931fe3ce96d00c3\\setup.py'"'"'; __file__='"'"'C:\\Users\\kaphl\\AppData\\Local\\Temp\\pip-install-hr3tzs6r\\flashgamma_663340304374467a8931fe3ce96d00c3\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kaphl\AppData\Local\Temp\pip-record-9ma4oipb\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kaphl\.conda\envs\myenvironmentname1\Include\flashgamma'
         cwd: C:\Users\kaphl\AppData\Local\Temp\pip-install-hr3tzs6r\flashgamma_663340304374467a8931fe3ce96d00c3\
    Complete output (35 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\flashgamma
    copying flashgamma\algorithms.py -> build\lib.win-amd64-3.9\flashgamma
    copying flashgamma\distribution.py -> build\lib.win-amd64-3.9\flashgamma
    copying flashgamma\helpers.py -> build\lib.win-amd64-3.9\flashgamma
    copying flashgamma\__init__.py -> build\lib.win-amd64-3.9\flashgamma
    running build_ext
    building 'flashgamma.gamma_evaluation_c' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\flashgamma
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\kaphl\.conda\envs\myenvironmentname1\lib\site-packages\numpy\core\include -Ic:\users\kaphl\.conda\envs\myenvironmentname1\include -Ic:\users\kaphl\.conda\envs\myenvironmentname1\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30037\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /Tcflashgamma/gamma_evaluation_c.c /Fobuild\temp.win-amd64-3.9\Release\flashgamma/gamma_evaluation_c.obj
    gamma_evaluation_c.c
    c:\users\kaphl\.conda\envs\myenvironmentname1\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
    flashgamma/gamma_evaluation_c.c(2923): warning C4018: '<': signed/unsigned mismatch
    flashgamma/gamma_evaluation_c.c(2935): warning C4018: '<': signed/unsigned mismatch
    flashgamma/gamma_evaluation_c.c(3194): warning C4244: '=': conversion from 'npy_intp' to 'int', possible loss of data
    flashgamma/gamma_evaluation_c.c(3205): warning C4018: '<': signed/unsigned mismatch
    flashgamma/gamma_evaluation_c.c(3217): warning C4018: '<': signed/unsigned mismatch
    flashgamma/gamma_evaluation_c.c(19801): error C2039: 'tp_print': is not a member of '_typeobject'
    c:\users\kaphl\.conda\envs\myenvironmentname1\include\cpython/object.h(193): note: see declaration of '_typeobject'
    flashgamma/gamma_evaluation_c.c(19806): error C2039: 'tp_print': is not a member of '_typeobject'
    c:\users\kaphl\.conda\envs\myenvironmentname1\include\cpython/object.h(193): note: see declaration of '_typeobject'
    flashgamma/gamma_evaluation_c.c(19821): error C2039: 'tp_print': is not a member of '_typeobject'
    c:\users\kaphl\.conda\envs\myenvironmentname1\include\cpython/object.h(193): note: see declaration of '_typeobject'
    flashgamma/gamma_evaluation_c.c(19834): error C2039: 'tp_print': is not a member of '_typeobject'
    c:\users\kaphl\.conda\envs\myenvironmentname1\include\cpython/object.h(193): note: see declaration of '_typeobject'
    flashgamma/gamma_evaluation_c.c(20434): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
    flashgamma/gamma_evaluation_c.c(20450): warning C4996: '_PyUnicode_get_wstr_length': deprecated in 3.3
    flashgamma/gamma_evaluation_c.c(22022): warning C4996: 'PyUnicode_FromUnicode': deprecated in 3.3
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30037\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\kaphl\.conda\envs\myenvironmentname1\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\kaphl\\AppData\\Local\\Temp\\pip-install-hr3tzs6r\\flashgamma_663340304374467a8931fe3ce96d00c3\\setup.py'"'"'; __file__='"'"'C:\\Users\\kaphl\\AppData\\Local\\Temp\\pip-install-hr3tzs6r\\flashgamma_663340304374467a8931fe3ce96d00c3\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\kaphl\AppData\Local\Temp\pip-record-9ma4oipb\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\kaphl\.conda\envs\myenvironmentname1\Include\flashgamma' Check the logs for full command output.

(MyEnvironmentName1) C:\WINDOWS\system32>`

**Comment by keithoffer** [comment]
I had a quick google, looks like this might be due to the module being designed for an older version of Python. Python 3.8 might work for you.

**Comment by samumonin** [comment]
I tried to pip install flashgamma (anaconda prompt) but it shows the following error. I have Python 3.8 but it doesn't work.
Any solution to solve this issue?


ERROR: Command errored out with exit status 1:
     command: /Users/samumonin/opt/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hd/8w5rxg_s49bcwg7p18wv3cs40000gn/T/pip-install-4mrbsqyx/flashgamma_f62d4daebd604a5dbd84dc5cfd3c410b/setup.py'"'"'; __file__='"'"'/private/var/folders/hd/8w5rxg_s49bcwg7p18wv3cs40000gn/T/pip-install-4mrbsqyx/flashgamma_f62d4daebd604a5dbd84dc5cfd3c410b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/hd/8w5rxg_s49bcwg7p18wv3cs40000gn/T/pip-pip-egg-info-fjmj8flq
         cwd: /private/var/folders/hd/8w5rxg_s49bcwg7p18wv3cs40000gn/T/pip-install-4mrbsqyx/flashgamma_f62d4daebd604a5dbd84dc5cfd3c410b/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hd/8w5rxg_s49bcwg7p18wv3cs40000gn/T/pip-install-4mrbsqyx/flashgamma_f62d4daebd604a5dbd84dc5cfd3c410b/setup.py", line 27, in <module>
        extensions = cythonize(extensions)
      File "/Users/samumonin/opt/anaconda3/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 970, in cythonize
        module_list, module_metadata = create_extension_list(
      File "/Users/samumonin/opt/anaconda3/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/Users/samumonin/opt/anaconda3/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'flashgamma/gamma_evaluation_c.pyx' doesn't match any files
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b3/e0/eaa5f2a4880c76679b24a72b58796288d61e883b80497dddd0db3e0c1e9f/flashgamma-0.0.1.tar.gz#sha256=68d214ed92854505b6987d28fe180de3f834900236cbc02316a9d04f08907a2e (from https://pypi.org/simple/flashgamma/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement flashgamma (from versions: 0.0.1)
ERROR: No matching distribution found for flashgamma
